# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lgotm < Formula
  desc "lgotm is a command for generation LGTM image and generated image is copied to clipboard."
  homepage "https://github.com/johnmanjiro13/lgotm"
  version "0.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/johnmanjiro13/lgotm/releases/download/v0.5.0/darwin-amd64"
      sha256 "5d50462d2de038f7a6498708d8e5657ce73bb71f4c42c0ffd14940d64b63003b"

      def install
        bin.install "darwin-amd64" => "lgotm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/johnmanjiro13/lgotm/releases/download/v0.5.0/darwin-arm64"
      sha256 "9f631a25453e24fa97fc27e91772e6de560484cccdd8ac3299ea690bd2b9ed1c"

      def install
        bin.install "darwin-arm64" => "lgotm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/johnmanjiro13/lgotm/releases/download/v0.5.0/linux-amd64"
      sha256 "66b7b53a76df9b2389cb9494c00743dcdae022ff62b1abb41c8273ba8e42bad3"

      def install
        bin.install "linux-amd64" => "lgotm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/johnmanjiro13/lgotm/releases/download/v0.5.0/linux-arm64"
      sha256 "5eb779bded778f69a416f7854d1dfd1bbd1646d36e315466ff81f428b48eef02"

      def install
        bin.install "linux-arm64" => "lgotm"
      end
    end
  end

  test do
    system "#{bin}/lgotm version"
  end
end
